containers:
    - name: app
      image: ghcr.io/tanyav2/simple-container-private:latest@sha256:d699a189a47c0cabfe42f89f41bc99e4d7c43ba47c4efca8b3ec5df4a991510d
      args: []
      env:
        - APP_NAME=tinfoil-test-app
        - LOG_LEVEL=debug
        - MAX_TOKENS=100
      secrets:
        - TINFOIL_API_KEY
memory: 8192
cpus: 4
gpus: 0
